---
- name: Setting up the environment
  hosts: [baby]
  remote_user: root
  gather_facts: False
  vars:
    node_version: 11.x

  tasks:
    - name: fetch Node.js package
      shell: curl -sL https://deb.nodesource.com/setup_{{ node_version }} | sudo -E bash -

    - name: install Node.js, git, nginx
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - nodejs
        - git
        - nginx

    - name: NODE | Install pm2
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

    - name: NODE | Install serve
      npm:
        name: serve
        global: yes
        production: yes
        state: present
